name: Continuous integration
on:
  pull_request:
    branches:
      - main
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Linting
        run: yarn lint
      - name: Run the tests
        run: yarn test:ci
      - name: Build
        run: yarn build
      - name: Coveralls
        uses: yarn run test:coveralls
